### ISSUE TITLE
NoSuchMethodError when running parquet-tools locally

### ISSUE THREAD

**Issue by panthony** [spotify/gcs-tools#12]
Hello there 👋 

Following the README, I tried to build the project & use it locally but `parquet-tools` fails with a `NoSuchMethodError`:

The command:
```
% java -jar parquet-tools/target/scala-2.12/parquet-tools-1.10.1.jar rowcount --debug gs://path/to/parquet/file
```

The error:
```
java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase$ParentTimestampUpdateIncludePredicate.create(GoogleHadoopFileSystemBase.java:790)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createOptionsBuilderFromConfig(GoogleHadoopFileSystemBase.java:2140)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1832)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:1013)
        at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:976)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.parquet.tools.command.RowCountCommand.execute(RowCountCommand.java:83)
        at org.apache.parquet.tools.Main.main(Main.java:223)
java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToList(Ljava/lang/CharSequence;)Ljava/util/List;
```

**Comment by nevillelyh** [comment]
@panthony sorry overlooked this forever. Can you give #13 a try?

**Comment by panthony** [comment]
@nevillelyh Using master it now works but it prints lots of warning too (which can be suppressed using ` --illegal-access=deny`):

```
➜  gcs-tools git:(master) java -jar parquet-tools/target/scala-2.12/parquet-tools-1.11.0.jar rowcount gs://path/to/parquet
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.hadoop.security.authentication.util.KerberosUtil (file:/path/to/gcs-tools/parquet-tools/target/scala-2.12/parquet-tools-1.11.0.jar) to method sun.security.krb5.Config.getInstance()
WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.security.authentication.util.KerberosUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Total RowCount: 462
```

**Comment by nevillelyh** [comment]
I can reproduce with JDK 11 but not JDK 8. We're still using JDK 8 since many data processing frameworks aren't compatible with 11 yet. Also probably because I used Hadoop 2 binding which is still on Java 8 (partly because Avro 1.8 still depends on Hadoop 2). Doesn't look like it's fixable right now.

https://stackoverflow.com/questions/52155078/how-to-fix-hadoop-warning-an-illegal-reflective-access-operation-has-occurred-e

I can look into Hadoop 3.3 but might run into issues since Avro & Parquet have outdated dependencies. And most frameworks are stuck on Avro 1.8 since 1.9+ has breaking changes. 🤷

**Comment by panthony** [comment]
@nevillelyh Fair enough, I switched back to JDK11 unexpectedly actually (lost my JAVA_HOME somewhere).

 It does works without warning with JDK8!
