### ISSUE TITLE
no JSON input found: gcloud credentials

### ISSUE THREAD

**Issue by ckchow** [spotify/gcs-tools#8]
on gcs-avro-tools 0.1.7 from homebrew, there appear to be issues loading the application default credentials.

```
Exception in thread "main" java.lang.IllegalArgumentException: no JSON input found
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
	at com.google.api.client.json.JsonParser.startParsing(JsonParser.java:222)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:379)
	at com.google.api.client.json.JsonParser.parse(JsonParser.java:335)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:165)
	at com.google.api.client.json.JsonParser.parseAndClose(JsonParser.java:147)
	at com.google.api.client.json.JsonFactory.fromInputStream(JsonFactory.java:206)
	at com.google.api.client.extensions.java6.auth.oauth2.FileCredentialStore.loadCredentials(FileCredentialStore.java:154)
	at com.google.api.client.extensions.java6.auth.oauth2.FileCredentialStore.<init>(FileCredentialStore.java:86)
	at com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromFileCredentialStoreForInstalledApp(CredentialFactory.java:301)

....
```

when I `gcloud auth application-default login`, it saves my credentials to `/Users/cchow/.config/gcloud/application_default_credentials.json`. did the expected path change?

**Comment by nevillelyh** [comment]
I can't reproduce this. I have credentials in the same path and have done `gcloud auth application-default login`. 

https://github.com/GoogleCloudPlatform/bigdata-interop/blob/v1.6.3/util/src/main/java/com/google/cloud/hadoop/util/CredentialFactory.java#L332

Looks like it might be reading `~/.credentials/storage.json`, which I have. Can you double check?

**Comment by nevillelyh** [comment]
No response for a long time. Closing. Feel free to re-open if you can reliably reproduce.

**Comment by enzo-paradigmtesting** [comment]
Aww :(
